name: Python Smart Home System CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    
    - name: Run tests with coverage
      run: |
        mkdir -p logs
        coverage run -m unittest discover tests/
        coverage report
    
    - name: Archive log files
      if: always()  # This ensures logs are saved even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-logs-python-${{ matrix.python-version }}
        path: |
          logs/
          *.log
          smart_home_system.log
        retention-days: 7
